name: easy_calendar
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: 4.0.3
  cupertino_icons: 1.0.2
  equatable: 2.0.5
  dartz: 0.10.1
  dio: 4.0.6
  flutter_bloc: 8.1.4
  get_it: 7.2.0
  flutter_svg: 1.1.6
  mask_text_input_formatter: 2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.4.0

  flutter_lints: 2.0.0
  build_runner: 2.3.3
  http_mock_adapter: 0.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/vectors/no_reminder_vector.svg
